config/routes.rb
Rails.application.routes.draw do
   root to: "pages#index"

	get 'about', to: 'pages#about'

  resources :shows do
  	resources :reviews
  end
 

end

app/models/review.rb
class Review < ActiveRecord::Base
	validates :title, presence: true
	validates :show, presence: true
	validates :author, presence: true
	validates :date_published, presence: true
	validates :recommend, presence: true
	validates :copy, presence: true
	validates :rating, presence: true
	validates :content, presence: true
end

app/models/show.rb
class Show < ActiveRecord::Base
	validates :title, presence: true, uniqueness: true
	validates :number_of_seasons, presence: true
	validates :status, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@shows = Show.all
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	def index
	     @reviews = Review.all
	end 


	def show
	     @review = Review.find(params[:id])
	end


	def new	 	     
	     @review = Review.new
	     @show = Show.find(params[:show_id])	 
	end


	def create		
	     @show = Show.find(params[:show_id])
	     @review = Review.new(review_params)
		if @review.save
		    redirect_to show_path(@show.id)
		else
		     @message = @review.errors.messages
		    render :new	
		end 
	end


	def edit
	     @show = Show.find(params[:show_id])
	     @review = Review.find(params[:id])
	end

	
	def update
		 @show = Show.find(params[:show_id])
		@review = Review.find(params[:id])
		if @review.update(review_params)
			redirect_to show_path(@show.id)
		else
			@message = @review.errors.messages
			render :edit
		end
	end


	def destroy
		@show = Show.find(params[:show_id])
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to show_path(@show.id)
	end


	def review_params
	     params.require(:review).permit!
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
	def index
		@shows = Show.all
	end

	def new
		@show = Show.new		
	end

	def create
		@show = Show.new(show_params)					
		if @show.save
			redirect_to show_path(@show.id)
		else
			@message = @show.errors.messages
			render :new
		end
	end

	def edit
		@show = Show.find(params[:id])
	end

	def update
		@show = Show.find(params[:id])		
		if @show.update(show_params)
			redirect_to show_path
		else
			@message = @show.errors.messages
			render :edit
		end
	end

	def show
		@show = Show.find(params[:id])
		@reviews = Review.all
				
	end

	def destroy
		@show = Show.find(params[:id])
		@show.destroy
		redirect_to shows_path
	end

	def show_params
		params.require(:show).permit!
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wiki TV" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand">wiki TV</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>         
    </ul>   
	  <ul class="nav navbar-nav">
      <li><%= link_to "All Shows", shows_path %></li>       
    </ul>
	  <ul class="nav navbar-nav">
      <li><%= link_to "Add Show", new_show_path %></li>         
    </ul>  
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About", about_path %></li>      
    </ul>
  </div>
</div>

    <div class="container-body">                    
            <%= yield %>
          </div>
         
        
       

      <footer>
        <p><center>&copy; Company 2014</center></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/about.html.erb
<html>
	<head>	
		<style>
			.container-body{		
			width: 900px; margin:0 auto;
			background-color: white;		
			align-content: center;	
			padding-top: 20px;		
			padding-left: 20px;
			padding-bottom: 20px;
			padding-right: 20px;			
						}

			.submit{
			
}

		body{
			background-color: #ddd;
}
		</style>
	</head>
	<body>	
			<div class="jumbotron1">
			  <h1>wiki TV</h1>
			  <p>wiki TV™ is a web-based database for information regarding television series. This site is free for everyone to read content about a TV series, start a new page for a new TV series and write reviews. wiki TV™ was originally just a project that was required in a web application class in Ateneo de Manila University, but Justin Bautista and Shannon Ching, the founders, saw a future in it. By undergoing a rigorous development process, what was once a site that catered only to users based in localhost:3000 has now reached global fame and success.</p>		
			</div>


		<div> <%= button_to "All Shows", shows_path, :class => "btn btn-primary", :method => "get" %> </div>
	</body>
</html>

app/views/pages/index.html.erb
<html>
<head>
		<style>
			body {
	background-color: #ddd;
}				
		</style>
	</head>
<div class="jumbotron">
  <h1>wiki TV</h1>
  <p>This is a wiki site for TV shows.</p>
  <p><a href="shows" class="btn btn-primary btn-lg">All Shows</a></p>
</div>
</html>

app/views/reviews/_form.html.erb
<html>
	<head>	
		<style>
			.container-body{		
			width: 900px; margin:0 auto;
			background-color: white;		
			align-content: center;
			padding-top: 20px;		
			padding-left: 20px;
			padding-bottom: 20px;	
			padding-right: 20px;		
						}

		body{
			background-color: #ddd;
}	
		</style>
	</head>
	<body>	
<%= form_for @review, url: {action: "create"} do |r| %>	
	<div><h4>TV Show:</h4></div>
	<%= r.text_field :show, :value => @show.title %>
	<div><h4>Title</h4></div>
	<%= r.text_field :title %>	
	<div><h4>Author</h4></div>
	<%= r.text_field :author %>
	<div><h4>Date Published</h4></div>
	<%= r.date_select :date_published %>	
	<div><h4>Content</h4></div>
	<%= r.text_area :content, size:"80x10" %>
	<div><h4>Rating</h4></div>
	<%= r.radio_button(:rating, "1") %>
	<%= label_tag("1") %>	
       	<%= r.radio_button(:rating, "2") %>	
	<%= label_tag("2") %>
	<%= r.radio_button(:rating, "3") %>
	<%= label_tag("3") %>	
       	<%= r.radio_button(:rating, "4") %>	
	<%= label_tag("4") %>	
	<%= r.radio_button(:rating, "5") %>
	<%= label_tag("5") %>	
       	<%= r.radio_button(:rating, "6") %>	
	<%= label_tag("6") %>	
	<%= r.radio_button(:rating, "7") %>
	<%= label_tag("7") %>	
       	<%= r.radio_button(:rating, "8") %>	
	<%= label_tag("8") %>	
	<%= r.radio_button(:rating, "9") %>
	<%= label_tag("9") %>	
       	<%= r.radio_button(:rating, "10") %>	
	<%= label_tag("10") %>	
	 		
	<div><h4>Recommended?</h4></div>
	<%= r.radio_button(:recommend, "Yes") %>
	<%= label_tag("Yes") %>	
       	<%= r.radio_button(:recommend, "No") %>	
	<%= label_tag("No") %>	
	<div><h4>Do you have a copy of this series?</h4></div>
	<%= r.radio_button(:copy, "Yes") %>
	<%= label_tag("Yes") %>	
       	<%= r.radio_button(:copy, "No") %>	
	<%= label_tag("No") %>	
	<hr>
	<%= r.submit "Save", class: "btn btn-primary" %>
<% end %>

</body>
</html>

app/views/reviews/_form1.html.erb
<html>
	<head>	
		<style>
			.container-body {		
			width: 900px; margin:0 auto;
			background-color: white;		
			align-content: center;
			padding-top: 20px;					
			padding-left: 20px;
			padding-bottom: 20px;	
			padding-right: 20px;		
						}

		body{
			background-color: #ddd;
}
		</style>
	</head>
	<body>	
			<%= form_for @review, url: {action: "update"} do |r| %>	
			<div><h4>TV Show:</h4></div>
			<%= r.text_field :show, :value => @show.title %>
			<div><h4>Title</h4></div>
			<%= r.text_field :title %>	
			<div><h4>Author</h4></div>			
			<%= r.text_field :author %>
			<div><h4>Date Published</h4></div>
			<%= r.date_select :date_published %>	
			<div><h4>Content</h4></div>
			<%= r.text_area :content, size:"80x10" %>
			<div><h4>Rating</h4></div>
			<%= r.radio_button(:rating, "1") %>
			<%= label_tag("1") %>	
			  	<%= r.radio_button(:rating, "2") %>	
			<%= label_tag("2") %>
			<%= r.radio_button(:rating, "3") %>
			<%= label_tag("3") %>	
			  	<%= r.radio_button(:rating, "4") %>	
			<%= label_tag("4") %>	
			<%= r.radio_button(:rating, "5") %>
			<%= label_tag("5") %>	
			  	<%= r.radio_button(:rating, "6") %>	
			<%= label_tag("6") %>	
			<%= r.radio_button(:rating, "7") %>
			<%= label_tag("7") %>	
			  	<%= r.radio_button(:rating, "8") %>	
			<%= label_tag("8") %>	
			<%= r.radio_button(:rating, "9") %>
			<%= label_tag("9") %>	
			  	<%= r.radio_button(:rating, "10") %>	
			<%= label_tag("10") %>		 					
			<div><h4>Recommended?</h4></div>
			<%= r.radio_button(:recommend, "Yes") %>
			<%= label_tag("Yes") %>	
			  	<%= r.radio_button(:recommend, "No") %>	
			<%= label_tag("No") %>	
			<div><h4>Do you have a copy of this series?</h4></div>
			<%= r.radio_button(:copy, "Yes") %>
			<%= label_tag("Yes") %>	
			  	<%= r.radio_button(:copy, "No") %>	
			<%= label_tag("No") %>	
			<hr>
			<%= r.submit "Save", class: "btn btn-primary" %>
		<% end %>		
	</body>
</html>

app/views/reviews/edit.html.erb
<html>

<h1>Edit Review</h1>
<hr>
<% if !@message.nil? %>
	 <% @message.each_pair do |key, value| %>
		ERROR: <%= "#{key}: #{value}" %> 
	<% end %>
<% end %>

<%= render partial: "reviews/form1", locals: { review: @review } %>
</html>

app/views/reviews/index.html.erb
<html>

<h1>Reviews</h1>
<hr>
<%= link_to "New Review", new_review_path %>
<hr>
<% @reviews.each do |review| %>
	<%= review.title %> | 
	<%= link_to "Edit", edit_review_path(review.id) %> |
	<%= link_to "Delete", review_path(review.id), method: :delete, data: { confirm: "Are you sure you want to delete?" } %>
<% end %>
</html>

app/views/reviews/new.html.erb
<html>

<h1>New Review</h1>
<hr>
<% if !@message.nil? %>
	 <% @message.each_pair do |key, value| %>
		ERROR: <%= "#{key}: #{value}" %> 
	<% end %>
<% end %>


<%= render partial: "reviews/form", locals: { review: @review } %>
</html>

app/views/shows/_form.html.erb
<html>
	<head>	
		<style>
			.container-body{		
			width: 900px; margin:0 auto;
			background-color: white;		
			align-content: center;	
			padding-top: 20px;		
			padding-left: 20px;
			padding-bottom: 20px;
			padding-right: 20px;			
						}

			.submit{
			
}

		body{
			background-color: #ddd;
}
		</style>
	</head>
	<body>	
																								
					<%= form_for show do |f| %>
					<div><h4>Title</h4></div>
					<%= f.text_field :title %>
					<div><h4>Number of Seasons</h4></div>
					<%= f.text_field :number_of_seasons %>
					<div><h4>Description</h4></div>
					<%= f.text_area :description, size: "80x10" %>
					<div><h4>Status</h4></div>
						<%= f.radio_button(:status, "Ongoing") %>
						<%= label_tag("Ongoing") %>	
					  		<%= f.radio_button(:status, "Finished") %>	
						<%= label_tag("Finished") %>	
					<div><h4>Episode Length</h4></div>										
					<%= f.text_field :episode_length %> minutes
					<div><h4>Actors</h4></div>
					<%= f.text_field :actors %>
					<div><h4>Producers</h4></div>
					<%= f.text_field :producers %>						
					  	<div><h4>Poster</h4></div>
					<%= f.text_field :poster %>	
					<hr>
					<%= f.submit "Save", class: "btn btn-primary" %>
				<% end %>													
	
	</body>
</html>

app/views/shows/edit.html.erb
<html>

<h1>Edit Show</h1>
<hr>
<% if !@message.nil? %>
	 <% @message.each_pair do |key, value| %>
		ERROR: <%= "#{key}: #{value}" %> 
	<% end %>
<% end %>

<%= render partial: "shows/form", locals: { show: @show } %>
</html>

app/views/shows/index.html.erb
<html>
	<head>
		<style>
			body {
	background-color: #ddd;
}				
		</style>
	</head>
	<body>
		<div class="jumbotron">
  <h1>wiki TV</h1>
  <p>This is a wiki site for TV shows.</p>
  <p><a <a href="shows/new" class="btn btn-primary btn-lg">Add Show</a></p>
</div>
	<table class="table table-striped table-hover ">
  <thead>
   
  </thead>
  <tbody>
	<tr>
		<td><b>Show Title</b></td>
		<td><b></b></td>
		<td><b></b></td>

	</tr>
<% @shows.each do |show| %>
	<tr>
	<td><%= link_to show.title, show_path(show.id) %></td>
	<td><%= link_to "Edit", edit_show_path(show.id) %></td>
	<td><%= link_to "Delete", show_path(show.id), method: :delete, data: { confirm: "Are you sure you want to delete?" } %></td>
	</tr>
<% end %>
	</tbody>
	</table>
	</body>
</html>

app/views/shows/new.html.erb
<html>

<h1>New Show</h1>
<hr>
<% if !@message.nil? %>
	 <% @message.each_pair do |key, value| %>
		ERROR: <%= "#{key}: #{value}" %> 
	<% end %>
<% end %>


<%= render partial: "shows/form", locals: { show: @show } %>
</html>
	

app/views/shows/show.html.erb
<html>
<head>	
		<style>
			.container-body{		
			width: 900px; margin:0 auto;
			background-color: white;		
			align-content: center;	
			padding-top: 20px;		
			padding-left: 20px;
			padding-bottom: 20px;
			padding-right: 20px;			
						}

			.submit{
			
}

		body{
			background-color: #ddd;
}
		</style>
	</head>
<body>
<h1><%= @show.title %></h1>
<% if @show.poster == "" %>
	<div class="jumbotron1">
  <h1>NO POSTER</h1>
  <p>If you have free time and I'm sure you do, please upload a poster ASAP. Thank you!</p>
  <p><a <a href="<%=@show.id%>/edit" class="btn btn-primary btn-lg">Edit Show</a></p>
</div>
<% else %>
<div class="jumbotron1" >  
	<img src = "<%= @show.poster %>" style="width: 800px; length:400px" />  
</div>
<% end %>




<h4>Description</h4>
<div><p><%= @show.description %></p></div>
<h4>Number of Season: <%= @show.number_of_seasons %> Seasons </h4> 
<h4>Status: <%= @show.status %></h4>
<h4>Episode Length: <%= @show.episode_length %> minutes</h4>
<h4>Actors: <%= @show.actors %></h4>
<h4>Producers: <%= @show.producers %></h4>


<hr>
<h1>Reviews</h1>


<% @reviews.each do |r| %>
	<% if r.show == @show.title %>
	<hr>	
	<div><b><%=r.title%></b></div>
	<div>by <%= r.author %></div>
	<div>Date: <%=r.date_published%></div>
	<div><p><%=r.content%></p></div>
	<div>Rating: <%=r.rating%></div>
	<div>Recommended? <%=r.recommend%></div>
	<div>Copy? <%=r.copy%></div>
	<div><%= link_to "Edit", edit_show_review_path(@show.id, r.id) %> |
	<%= link_to "Delete", show_review_path(@show.id, r.id), method: :delete, data: { confirm: "Are you sure you want to delete?" } %></div>
	<% end %>
	
<% end %>
<hr>
<div class="buttons" style="padding-bottom: 30px">
	<div style="float: right; padding-bottom: 20 px">
	<%= button_to "All Shows", shows_path, :class => "btn btn-primary", :method => "get" %>
	</div>
	<div style="float: left; padding-bottom: 20 px" >
	<%= button_to "New Review", new_show_review_path(@show.id), :class => "btn btn-primary", :method => "get" %>
	</div>
</div>
</body>
</html>